<?php

define('PROVINCES', [
    'Nanggroe Aceh Darussalam' => ['Banda Aceh', 'Langsa', 'Lhokseumawe', 'Sabang', 'Subulussalam'],
    'Sumatera Utara' => ['Medan', 'Pematangsiantar', 'Sibolga', 'Tanjungbalai', 'Binjai', 'Padangsidempuan'],
    'Sumatera Selatan' => ['Palembang', 'Pagaralam', 'Lubuklinggau'],
    'Sumatera Barat' => ['Padang', 'Bukittinggi', 'Padangpanjang', 'Pariaman', 'Sawahlunto', 'Solok'],
    'Riau' => ['Pekanbaru', 'Dumai'],
    'Jambi' => ['Jambi', 'Sungai Penuh'],
    'Bengkulu' => ['Bengkulu', 'Curup', 'Lubuklinggau'],
    'Lampung' => ['Bandar Lampung', 'Metro'],
    'DKI Jakarta' => ['Jakarta'],
    'Banten' => ['Serang', 'Cilegon', 'Tangerang', 'Bekasi'],
    'Jawa Barat' => ['Bandung', 'Bekasi', 'Bogor', 'Cimahi', 'Cirebon', 'Depok', 'Sukabumi'],
    'Jawa Tengah' => ['Semarang', 'Pekalongan', 'Salatiga'],
    'DI Yogyakarta' => ['Yogyakarta'],
    'Jawa Timur' => ['Surabaya', 'Malang', 'Madiun', 'Mojokerto', 'Jombang'],
    'Bali' => ['Denpasar'],
    'Nusa Tenggara Barat' => ['Mataram'],
    'Nusa Tenggara Timur' => ['Kupang'],
    'Kalimantan Utara' => ['Tanjung Selor'],
    'Kalimantan Timur' => ['Samarinda'],
    'Kalimantan Selatan' => ['Banjarmasin'],
    'Kalimantan Tengah' => ['Palangka Raya'],
    'Kalimantan Barat' => ['Pontianak'],
    'Sulawesi Utara' => ['Manado'],
    'Sulawesi Tengah' => ['Palu'],
    'Sulawesi Selatan' => ['Makassar'],
    'Sulawesi Tenggara' => ['Kendari'],
    'Sulawesi Barat' => ['Mamuju'],
    'Maluku' => ['Ambon'],
    'Maluku Utara' => ['Sofifi'],
    'Papua' => ['Jayapura'],
    'Papua Barat' => ['Manokwari'],
    'Gorontalo' => ['Gorontalo'],
    'Kepulauan Riau' => ['Tanjung Pinang'],
    'Papua Selatan' => ['Merauke'],
    'Papua Tengah' => ['Nabire'],
    'Papua Pegunungan' => ['Jayawijaya'],
]);

?>